# Generated by Django 4.2.7 on 2023-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_body', models.TextField(blank=True, db_column='note_body', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'Note',
            },
        ),
    ]
